apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: disastrous-louse-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/disastrous-louse-dotnet-basic